version: "3.3"

services: 
  app:
    container_name: restonercomensales_app_servicio_complete_information
    restart: always 
    build: .
    networks:
      - backend
    ports:
      - "3100:3100"
    links:
      - postgres
  postgres:
    container_name: postgres_db
    restart: always
    image: "postgres:13"
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=postgres2
      - POSTGRES_DB=postgres2
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - backend
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminz2@adminz2.com
      PGADMIN_DEFAULT_PASSWORD: adminz2
    depends_on:
      - postgres
networks:
  backend:








